name: Restrict Main Branch

on:
  push:
    branches:
      - main

jobs:
  restrict-main:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure only 'develop' can be merged
        run: |
          if [ "$(git log -1 --pretty=%P)" != "$(git merge-base HEAD origin/develop)" ]; then
            echo "Only 'develop' branch can be merged into 'main'."
            exit 1
          fi
