variables:
  DOCKER_IMAGE: node:22-alpine

lint:
  image: $DOCKER_IMAGE
  stage: .pre
  script:
    - yarn install
    - yarn lint

deploy_to_main:
  image: $DOCKER_IMAGE
  stage: deploy
  script:
    - apk add --no-cache git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"
    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git fetch origin
    - git checkout -B main origin/main
    - git merge --no-ff origin/develop -m "Merge develop into main via CI/CD"
    - git push origin main
  only:
    - develop
  when: manual
  environment:
    name: production
