name: Restrict Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure only 'qa' can be merged to 'main'
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          if [ "$SOURCE_BRANCH" != "qa" ]; then
            echo "Error: Only the 'qa' branch can be merged into 'main'. Your source branch is '$SOURCE_BRANCH'."
            exit 1
          fi
          echo "Source branch is 'qa'. Proceeding with PR checks."
